#!/bin/sh

# check the fstab for the required wombatforenics entry.
fstabbool=0
while IFS='' read -r line; do
    if [ "$line" = "/tmp/wombatforensics/currentwfc /tmp/wombatforensics/mntpt auto defaults,rw,users,noauto 0 0" ]; then
        fstabbool=1
    fi
done <"/etc/fstab"
if [ $fstabbool -eq 0 ]; then
    echo "/tmp/wombatforensics/currentwfc /tmp/wombatforensics/mntpt auto defaults,rw,users,noauto 0 0" >> /etc/fstab
fi

# pretty sure i just create these as the user... since it's links.
# check for the existence of the mntpt directory. create it if it doesn't exist.
#mkdir -p /tmp/wombatforensics/mntpt
# allow non root modify for the currentwfc bit.
#chmod o+rw /tmp/wombatforensics
