#ifndef WOMBATINCLUDE_H
#define WOMBATINCLUDE_H

#include <bitset>
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <QApplication>
#include <QActionGroup>
#include <QBoxLayout>
#include <QByteArray>
#include <QDebug>
#include <QDialog>
#include <QDir>
#include <QFileDialog>
#include <QFrame>
#include <QFuture>
#include <QFutureWatcher>
#include <QInputDialog>
#include <QList>
#include <QMainWindow>
#include <QMessageBox>
#include <QObject>
#include <QSizePolicy>
#include <QtSql/QtSql>
#include <QSqlDatabase>
#include <QSqlError>
#include <QSqlQuery>
#include <QSqlQueryModel>
#include <QSqlRecord>
#include <QStandardItem>
#include <QStandardItemModel>
#include <QStatusBar>
#include <QString>
#include <QStringList>
#include <QThreadPool>
#include <QTreeWidgetItem>
#include <QVector>
#include <QWebElement>
#include <QWebFrame>
#include <QWebView>
#include <QtConcurrent>
#include <QtPlugin>
#include <QtWebKitWidgets>
#include <QtWidgets>
#include <sstream>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <sys/stat.h>

#include "tskvariable.h"
#include "translate.h"
#include "hexeditor.h"

#include "tsk/libtsk.h"
#include "img/aff.h"
#include "afflib.h"
#include "img/ewf.h"
#include "libewf.h"
#include "vs/tsk_bsd.h"
#include "vs/tsk_mac.h"
#include "vs/tsk_sun.h"
#include "vs/tsk_gpt.h"
#include "fs/tsk_ntfs.h"
#include "fs/tsk_exfatfs.h"
#include "fs/tsk_fatfs.h"
#include "fs/tsk_fatxxfs.h"
#include "fs/tsk_ffs.h"
#include "fs/tsk_ext2fs.h"
#include "fs/tsk_iso9660.h"
#include "fs/tsk_hfs.h"
#include "fs/tsk_yaffs.h"
#endif // WOMBATINCLUDE_H
