#ifndef WOMBATINCLUDE_H
#define WOMBATINCLUDE_H

#include <bitset>
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <QtAV/QtAV.h>
#include <QtAVWidgets>
#include <QAbstractItemModel>
#include <QAbstractListModel>
#include <QApplication>
#include <QActionGroup>
#include <QBoxLayout>
#include <QByteArray>
#include <QDebug>
#include <QDialog>
#include <QDir>
#include <QFileDialog>
#include <QFrame>
#include <QFuture>
#include <QFutureWatcher>
#include <QGridLayout>
#include <QImage>
#include <QInputDialog>
#include <QList>
#include <QMainWindow>
#include <QMessageBox>
#include <QObject>
#include <QSizePolicy>
#include <QtSql/QtSql>
#include <QSqlDatabase>
#include <QSqlError>
#include <QSqlQuery>
#include <QSqlQueryModel>
#include <QSqlRecord>
#include <QStatusBar>
#include <QString>
#include <QStringList>
#include <QTextBlock>
#include <QTextCodec>
#include <QTextCursor>
#include <QTextEdit>
#include <QThread>
#include <QThreadPool>
#include <QTreeWidgetItem>
#include <QVector>
#include <QWebElement>
#include <QWebFrame>
#include <QWebView>
#include <QtConcurrent>
#include <QtPlugin>
#include <QtWebKitWidgets>
#include <QtWidgets>
#include <QMouseEvent>
#include <QFocusEvent>
#include <QResizeEvent>
#include <QKeyEvent>
#include <QPaintEvent>
#include <QWidget>
#include <QPainter>
#include <QPixmap>

#include <sstream>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <sys/stat.h>
#include <sys/types.h>
#include <stdexcept>
#include <vector>

#include <math.h>
#include <assert.h>
#include <errno.h>
#include <ctype.h>
#include <algorithm>
#include <new>
#include <unistd.h>
#include <string.h>

#include "tskvariable.h"
#include "cursor.h"

#include "tsk/libtsk.h"
#include "img/aff.h"
#include "afflib.h"
#include "img/ewf.h"
#include "libewf.h"
#include "vs/tsk_bsd.h"
#include "vs/tsk_mac.h"
#include "vs/tsk_sun.h"
#include "vs/tsk_gpt.h"
#include "fs/tsk_ntfs.h"
#include "fs/tsk_exfatfs.h"
#include "fs/tsk_fatfs.h"
#include "fs/tsk_fatxxfs.h"
#include "fs/tsk_ffs.h"
#include "fs/tsk_ext2fs.h"
#include "fs/tsk_iso9660.h"
#include "fs/tsk_hfs.h"
#include "fs/tsk_yaffs.h"
#include "magic.h"
//#include "qdebugstream.h"

#endif // WOMBATINCLUDE_H
