#ifndef WOMBATINCLUDE_H
#define WOMBATINCLUDE_H

// Copyright 2013-2019 Pasquale J. Rinaldi, Jr.
// Distrubted under the terms of the GNU General Public License version 2

#include <bitset>
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <QAbstractItemModel>
#include <QAbstractListModel>
#include <QApplication>
#include <QActionGroup>
#include <QBoxLayout>
#include <QByteArray>
#include <QDateTime>
#include <QDebug>
#include <QDialog>
#include <QDir>
#include <QFile>
#include <QFileDialog>
#include <QFrame>
#include <QFuture>
#include <QFutureWatcher>
#include <QGridLayout>
#include <QImage>
#include <QInputDialog>
#include <QLineEdit>
#include <QIODevice>
//#include <QJsonDocument>
//#include <QJsonObject>
#include <QList>
#include <QMainWindow>
//#include <QMediaPlayer>
#include <QMessageBox>
#include <QMutex>
#include <QObject>
#include <QProgressBar>
#include <QSizePolicy>
#include <QSlider>
//#include <QtSql/QtSql>
//#include <QSqlDatabase>
//#include <QSqlError>
//#include <QSqlQuery>
//#include <QSqlQueryModel>
//#include <QSqlRecord>
#include <QStatusBar>
#include <QString>
#include <QStringList>
#include <QTextBlock>
#include <QTextCodec>
#include <QTextCursor>
#include <QTextEdit>
#include <QTextStream>
#include <QThread>
#include <QThreadPool>
#include <QTimeZone>
#include <QTreeWidgetItem>
#include <QVector>
#include <QtConcurrent>
//#include <QtPlugin>
#include <QtWidgets>
#include <QMouseEvent>
#include <QFocusEvent>
#include <QResizeEvent>
#include <QKeyEvent>
#include <QPaintEvent>
#include <QPainter>
#include <QPixmap>
//#include <QVideoWidget>
#include <QWebEngineView>
#include <QWidget>

#include <sstream>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <sys/mount.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <stdexcept>
#include <vector>
#include <math.h>
#include <assert.h>
#include <errno.h>
#include <ctype.h>
#include <algorithm>
#include <new>
#include <unistd.h>
#include <string.h>
#include <fcntl.h>
#include <tar.h>
#include <libtar.h>
#include <libewf.h>

#endif // WOMBATINCLUDE_H
