######################################################################
# Automatically generated by qmake (3.0) Wed Jul 31 11:21:44 2013
######################################################################

TEMPLATE = lib
QT += core gui widgets
CONFIG += plugin
CONFIG += debug
TARGET = basictools
INCLUDEPATH += .

# Input
HEADERS += basictools.h ../../interfaces.h
SOURCES += basictools.cpp
RESOURCES += basictools.qrc
DESTDIR = ../../../wombatforensics-output/debug/build/plugins
